services:
  nginx:
    image: nginxproxy/nginx-proxy:1.6
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - figurinhas_2026_acme:/etc/acme.sh
      - figurinhas_2026_certs:/etc/nginx/certs
      - figurinhas_2026_html:/usr/share/nginx/html
      - figurinhas_2026_dhparam:/etc/nginx/dhparam
      - figurinhas_2026_vhost:/etc/nginx/vhost.d
    networks:
      - figurinhas_2026_net

  acme:
    image: nginxproxy/acme-companion:2.4
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - figurinhas_2026_certs:/etc/nginx/certs
      - figurinhas_2026_html:/usr/share/nginx/html
      - figurinhas_2026_dhparam:/etc/nginx/dhparam
      - figurinhas_2026_vhost:/etc/nginx/vhost.d
    networks:
      - figurinhas_2026_net

  app:
    image: ${APP_IMAGE}
    environment:
      FLASK_DEBUG: "0"
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_SCHEMA: "app"

      APP_BASE_URL: "https://faltamquais.cloud"
      TRUSTED_HOSTS: "faltamquais.cloud,www.faltamquais.cloud"
      SESSION_COOKIE_SECURE: "true"

      PROXY_FIX_X_FOR: "1"
      PROXY_FIX_X_PROTO: "1"
      PROXY_FIX_X_HOST: "1"

      MAX_CONTENT_LENGTH: "1048576"

      RATELIMIT_STORAGE_URI: "redis://redis:6379/0"
      RATELIMIT_DEFAULT: "200 per minute; 2000 per hour"

      MAIL_SERVER: "smtp.gmail.com"
      MAIL_PORT: "587"
      MAIL_USE_TLS: "true"
      MAIL_USE_SSL: "false"
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}

      VIRTUAL_HOST: "faltamquais.cloud,www.faltamquais.cloud"
      VIRTUAL_PORT: "8000"
      LETSENCRYPT_HOST: "faltamquais.cloud,www.faltamquais.cloud"
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

      TZ: "America/Sao_Paulo"
    networks:
      - figurinhas_2026_net

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - figurinhas_2026_redis_data:/data
    networks:
      - figurinhas_2026_net

volumes:
  figurinhas_2026_certs:
  figurinhas_2026_html:
  figurinhas_2026_dhparam:
  figurinhas_2026_vhost:
  figurinhas_2026_acme:  
  figurinhas_2026_redis_data:

networks:
  figurinhas_2026_net:
    external: true